name: CMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cmake-version: [3.18.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          git submodule update --init --recursive
          git clone https://github.com/google/googletest.git

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: ${{ matrix.cmake-version }}

      - name: Configure CMake on Linux and macOS
        if: matrix.os != 'windows-latest'
        run: |
          cmake -S . -B build -DENABLE_TEST=ON
          cmake --build build --parallel
          build/pybind11_test

      # Windows
      - name: Configure CMake on Windows
        if: matrix.os == 'windows-latest'
        run: |
          cmake -G "Visual Studio 16 2019" -A x64 -S . -B build
          cmake --build build --config Release --parallel
          build/Release/pybind11_test.exe
